version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib


  build:
    commands:
      #creating zip files for  lamda-to-s3 fucntion
      # - echo "Zipping deployment package for Lambda Function enrichment-filter..."
      # - cd lib
      # - zip -r9 ../deployment_package_1.zip .
      # - cd ..
      # - cd enrichment-filter
      # - zip -g ../deployment_package_1.zip lamdba_function.py
      # - cd ..

      # #creating zip files for  lamda-to-s3 fucntion
      # - echo "Zipping deployment package for Lambda Function lamda-to-s3..."
      # - cd lib
      # - zip -r9 ../deployment_package_2.zip .
      # - cd ..
      # - cd lamda-to-s3
      # - zip -g ../deployment_package_2.zip lambda_function.py
      # - cd ..

      #creating zip files for mock-data-generator fucntion
      - echo "Zipping deployment package for mock-data-generator Function..."
      - cd lib
      - zip -r9 ../deployment_package_3.zip .
      - cd ..
      - cd mock-data-generator
      - zip -g ../deployment_package_3.zip generate_mock_airbnb.py
      - cd ..

  post_build:
    commands:
      - echo "Uploading deployment packages to S3..."

      # # Upload package for Lambda Function 1
      # - echo "Uploading deployment package deployment_package_1 to S3..."
      # - aws s3 cp deployment_package_1.zip s3://hh-lambda-builds-zip/
      # - echo "Updating Lambda Function AirBnB-enrichment-filter via S3..."
      # - aws lambda update-function-code --function-name AirBnB-enrichment-filter --s3-bucket hh-lambda-builds-zip --s3-key deployment_package_1.zip

      # # Upload package for Lambda Function 2
      # - echo "Uploading deployment package deployment_package_2 to S3..."
      # - aws s3 cp deployment_package_2.zip s3://hh-lambda-builds-zip/
      # - echo "Updating Lambda Function AirBnB-lambda-to-s3 via S3..."
      # - aws lambda update-function-code --function-name AirBnB-lambda-to-s3 --s3-bucket hh-lambda-builds-zip --s3-key deployment_package_2.zip

      # Upload package for Lambda Function 3
      - echo "Uploading deployment package deployment_package_3 to S3..."
      - aws s3 cp deployment_package_3.zip s3://hh-lambda-builds-zip/
      - echo "Updating Lambda Function ProduceAirbnbBookingData via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket hh-lambda-builds-zip --s3-key deployment_package_3.zip

      - echo "Deployment complete!"
